HW1
================
Bohan Zhu
2025-09-11

# Problem 1

``` r
library(moderndive)
data("early_january_weather")
```

``` r
names(early_january_weather)
```

    ##  [1] "origin"     "year"       "month"      "day"        "hour"      
    ##  [6] "temp"       "dewp"       "humid"      "wind_dir"   "wind_speed"
    ## [11] "wind_gust"  "precip"     "pressure"   "visib"      "time_hour"

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
mean(early_january_weather$temp)
```

    ## [1] 39.58212

There are 15 variables in this dataset, which are . There are 358 data
points in the data. Besides, the average temperature is 39.58 F.
