---
title: "P8105_HW1_bz2561"
author: "Bohan Zhu"
date: "2025-09-11"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
```

# Problem 1
```{r}
library(moderndive)
data("early_january_weather")
```


The dataset shows hourly meteorological data for LGA, JFK, and EWR for the month of January 2013. There are `r nrow(early_january_weather)` variables in this dataset, which are `r colnames(early_january_weather)`. There are `r ncol(early_january_weather)` data points in the data. Besides, the average temperature is `r mean(early_january_weather$temp)` F.

```{r}
ggplot(data = early_january_weather, aes(x = time_hour, y = temp, 
                                         color = humid)) + geom_point()
```
```{r}
ggsave("scatter_plot.pdf",height = 4,width = 6)
```

# Problem 2
```{r}
set.seed(123)
df1 =
  tibble(
    vec_numeric = rnorm(10),
    vec_logical = (ifelse(vec_numeric > 0, TRUE, FALSE)),
    vec_character = c("Math","Finance","Music","Art","Statistics","Physics",
                      "Marketing","Biology","Accounting","Literature"),
    vec_factor = c("STEM","Business","Humanities","Humanities","STEM","STEM",
                   "Business","STEM","Business","Humanities")
  )

df1
```

```{r}
mean(pull(df1, vec_numeric))
mean(pull(df1, vec_logical))
mean(pull(df1, vec_character))
mean(pull(df1, vec_factor))
```

